apiVersion: v1
kind: Service
metadata:
    name: api-gateway
spec:
    selector:
        app: api-gateway
    ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 80
        - protocol: TCP
          name: https
          port: 443
          targetPort: 443
    type: LoadBalancer
